image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # set up python dependencies and database
  - name: main terminal
    init: |
      cp ./.env.gitpod ./.env
      mysqladmin create greencheck
      source .venv/bin/activate
      python -m pip install -r requirements/requirements.linux.generated.txt
      dotenv run -- ./manage.py migrate
      dotenv run -- ./manage.py tailwind install
      dotenv run -- ./manage.py tailwind build
      cd ./apps/theme/static_src/
      npx rollup --config
      cd ../../../
      dotenv run -- ./manage.py collectstatic --no-input
    command: ls

  - name: rabbitmq
    command: >
      docker run 
      --hostname green-rabbit 
      -p 5672:5672 
      --rm
      --privileged
      --name green-rabbit 
      rabbitmq:3.11

  - name: mailhog
    command: >
      docker run
      --rm
      --name green-mailhog
      -p 8025:8025
      -p 1025:1025
      mailhog/mailhog

  - name: tailwind
    command: >
      echo
      "to run tailwind, type: make dev.tailwind.start"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: ignore
    # redis
  - port: 6379
    onOpen: ignore
    # rabbitmq
  - port: 5672
    onOpen: ignore
    # mysql
  - port: 3306
    onOpen: ignore
    # mailhog
  - port: 8025
    onOpen: ignore
    # debugging ports in vscode
  - port: 30000-50000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
