
services:
  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=deploy
      - MYSQL_DATABASE=greencheck
      - MYSQL_USER=deploy
      - MYSQL_PASSWORD=deploy
    expose:
      - 3306
  rabbitmq:
    image: rabbitmq:3.11
    restart: always
    expose:
      - 5672
    ports:
      - 5672:5672
  django:
    # uncomment to pass in your own .env file instead of using the environment variables below
    # env_file:
    # - path: ./.env.docker
    environment:
      - PORT=9000
      - GUNICORN_BIND_IP=0.0.0.0
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql://deploy:deploy@mariadb:3306/greencheck
      - DATABASE_URL_READ_ONLY=mysql://deploy:deploy@mariadb:3306/greencheck
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=greenweb.settings.development
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenweb-app
    image: greenweb-app
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ./apps:/app/apps
      - ./greenweb:/app/greenweb
    restart: always
    depends_on:
      - mariadb
      - rabbitmq
