---
name: Greencheck Test
author: James Camilleri <jcamilleri@scottlogic.com>
description: Scenario to test the Greencheck endpoint of the Green Web Foundation Greencheck API

version: "3.5"

networks:
  greencheck-network:

services:
  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    env:
      MYSQL_ROOT_PASSWORD: just-for-github-actions
      MYSQL_DATABASE: greencheck
    networks:
      - greencheck-network

  rabbitmq:
    image: rabbitmq:3.9
    env:
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
    ports:
      - 5672:5672
    options: '--hostname "rmq" --health-cmd "rabbitmqctl status" --health-interval 10s --health-timeout 10s --health-retries 3 --health-start-period 60s'
    networks:
      - greencheck-network

  django:
    depends_on:
      - mariadb
    build:
      context: .
      args:
        PIPENV_CFG: --dev
    command:
      - cp -a . .
      - python -m pip install --upgrade pipenv wheel
      - pipenv install --deploy --dev --verbose
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - greencheck-network

  test-container:
    container_name: test-container
    image: node 
    depends_on: django
    setup-commands:
      - cp ./green_metric_tests/greencheck_test.spec.js .
      - cp ./green_metric_tests/package.json .
      - npm install
    networks:
      - greencheck-network

  flow:
    - name: Greencheck API Test
      container: test-container
      commands:
        - type: console
          command: npm test
          note: Starting test
          read-notes-stdout: true
        - type: console
          command: sleep 30
          note: Idling
        - type: console
          command: npm test
          note: Starting test again