---
all:
  hosts:
    app1.thegreenwebfoundation.org:
      internal_ip: "10.0.0.5"
      dramatiq_threads: 2
      dramatiq_processes: 3
      sentry_sample_rate: 0
      app_name: app1
      gunicorn_workers: 4
      gunicorn_threads: 1

    app2.thegreenwebfoundation.org:
      internal_ip: "10.0.0.4"
      dramatiq_threads: 2
      dramatiq_processes: 3
      sentry_sample_rate: 0
      app_name: app2
      gunicorn_workers: 4
      gunicorn_threads: 1
    # TODO: once we have update the worker process names we can use app3 for serving production traffic
    # letting us decommission some of the older app servers
    app3.thegreenwebfoundation.org:
      internal_ip: "10.0.0.6"
      dramatiq_threads: 1
      dramatiq_processes: 1
      sentry_sample_rate: 0
      app_name: app3
      gunicorn_workers: 4
      gunicorn_threads: 1
    app4.thegreenwebfoundation.org:
      internal_ip: "10.0.0.7"
      dramatiq_threads: 2
      dramatiq_processes: 3
      sentry_sample_rate: 0
      app_name: app4
      gunicorn_workers: 4
      gunicorn_threads: 1

  vars:
    tgwf_stage: "prod"
    tgwf_domain_name: "admin"
    project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
    project_deploy_branch: "master"
    ansible_user: "deploy"
    service_user: "deploy"
    service_gunicorn_app: "web_{{ tgwf_stage }}"
    service_worker_job: "worker_{{ tgwf_stage }}"
    gunicorn_port: 9000

  # you can set child groups too
  children:
    app_servers:
      # within a child group, you need to define your hosts again
      # so it's clear which hosts you want to refer to
      hosts:
        app1.thegreenwebfoundation.org:
        app2.thegreenwebfoundation.org:
        app3.thegreenwebfoundation.org:
        app4.thegreenwebfoundation.org:
      # within the child group can define new vars which take
      # precedence over the ones further 'upstream'
      # vars:
      #   some_var: value_here
