---
app_servers:
  hosts:
    app1.thegreenwebfoundation.org:
      project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      tgwf_stage: "prod"
      tgwf_domain_name: admin
    app2.thegreenwebfoundation.org:
      project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      tgwf_stage: "prod"
      tgwf_domain_name: admin

all:
  hosts:
    app1.thegreenwebfoundation.org:
      project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      tgwf_stage: "prod"
      tgwf_domain_name: admin
    app2.thegreenwebfoundation.org:
      project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      tgwf_stage: "prod"
      tgwf_domain_name: admin
    hel1.thegreenwebfoundation.org:
        project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        tgwf_stage: "prod"
        tgwf_domain_name: admin


