---
all:
  hosts:
    app3.thegreenwebfoundation.org:
      internal_ip: "10.0.0.6"
      gunicorn_port: 10000
      dramatiq_threads: 1
      dramatiq_processes: 1
      sentry_trace_rate: 1
      app_name: "app-staging"
      gunicorn_workers: 4
      gunicorn_threads: 1
  vars:
    tgwf_stage: "staging"
    tgwf_domain_name: "admin-staging"
    project_root: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
    project_deploy_branch: "staging"
    ansible_user: "deploy"
    service_gunicorn_app: "web_{{ tgwf_stage }}"
    service_worker_job: "worker_{{ tgwf_stage }}"

  # you can set child groups too
  children:
    app_servers:
      # within a child group, you need to define your hosts again
      # so it's clear which hosts you want to refer to
      hosts:
        app3.thegreenwebfoundation.org:
      # within the child group can define new vars which take
      # precedence over the ones further 'upstream'
      # vars:
      #   some_var: value_here
