---
- name: Build minified tailwind css file
  ansible.builtin.shell: |
    source .venv/bin/activate
    dotenv run -- ./manage.py tailwind build
  args:
    chdir: "{{ project_root }}/current"
    executable: "/usr/bin/bash"
  changed_when: false

- name: Build javascript bundle with rollup, using the local config file
  ansible.builtin.command: "npx rollup --config"
  args:
    chdir: "{{ project_root }}/current/apps/theme/static_src"
  changed_when: false

- name: Collect static files for django
  ansible.builtin.shell: |
    source .venv/bin/activate
    dotenv run -- ./manage.py collectstatic --no-input
  args:
    chdir: "{{ project_root }}/current"
    executable: "/usr/bin/bash"
  changed_when: false
