---
- name: Set up a virtual environment for this project
  ansible.builtin.command: "python3.11 -m venv .venv"
  args:
    chdir: "{{ project_root }}/current"
  changed_when: false

- name: Install python dependencies with uv
  ansible.builtin.shell: |
    source .venv/bin/activate
    python3.11 -m pip install -r requirements/requirements.linux.generated.txt
  args:
    chdir: "{{ project_root }}/current"
    executable: "/usr/bin/bash"

- name: Update node deps for building tailwind
  ansible.builtin.shell: |
    source .venv/bin/activate
    dotenv run -- python3.11 ./manage.py tailwind update
  args:
    chdir: "{{ project_root }}/current"
    executable: "/usr/bin/bash"
  when: update_front_end_deps is true

- name: Install node deps for building tailwind
  ansible.builtin.shell: |
    source .venv/bin/activate
    dotenv run -- python3.11 ./manage.py tailwind install
  args:
    executable: "/usr/bin/bash"
    chdir: "{{ project_root }}/current"
  changed_when: false
