---
# shared steps for provisioning boxes, deploying and controlling
# how web workers and queue workers are scaled
- name: Set up script for running workers and web app, via systemd in project
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: deploy
    group: deploy
    mode: "0755"
  loop:
    - {
        src: "run_worker.sh.j2",
        dest: "{{ project_root }}/current/run_worker.sh",
      }
    - {
        src: "run_gunicorn.sh.j2",
        dest: "{{ project_root }}/current/run_gunicorn.sh",
      }
  become: true
  tags:
    - systemd
    - config

- name: Set up systemd entries for workers and web app
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: deploy
    group: deploy
    mode: "0755"
  loop:
    - {
        src: "systemd.web-app.service.j2",
        dest: "/etc/systemd/system/{{ service_gunicorn_app }}.service",
      }
    - {
        src: "systemd.worker.service.j2",
        dest: "/etc/systemd/system/{{ service_worker_job }}.service",
      }
  become: true
  tags:
    - systemd
    - config

- name: Reload systemd to pick up new changes
  ansible.builtin.systemd:
    daemon_reload: True
  become: true
  tags:
    - systemd
    - config
