---
- name: Set up directory for deploying django app
  ansible.builtin.file:
    path: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
    state: directory
    mode: "0755"
    owner: deploy
    group: deploy
  become: true

- name: Move .env file to shared directory
  ansible.builtin.template:
    src: "templates/dotenv.j2"
    dest: "{{ project_root }}/shared/.env"
    mode: "0755"
    owner: deploy
    group: deploy
  become: true

- name: Link .env to shared directory
  ansible.builtin.file:
    src: "{{ project_root }}/shared/.env"
    dest: "{{ project_root }}/current/.env"
    state: link

- name: Link ./media to shared ./media directory
  ansible.builtin.file:
    src: "{{ project_root }}/shared/media"
    dest: "{{ project_root }}/current/media"
    state: link

- name: Link ./data to shared ./data directory
  ansible.builtin.file:
    src: "{{ project_root }}/shared/data"
    dest: "{{ project_root }}/current/data"
    state: link

- name: Add symlink to .aws.credentials in shared directory
  ansible.builtin.file:
    src: "{{ project_root }}/shared/.aws.credentials"
    dest: "{{ project_root }}/current/.aws.credentials"
    state: link
