---
- name: Deploy the TGWF django admin
  hosts:
    - all
  remote_user: "deploy"
  become: no

  vars:
    project_git_repo: "git@github.com:thegreenwebfoundation/greenwebfoundation-admin.git"
    project_deploy_strategy: git
    project_version: "master"
    project_local_path: "../"
    project_has_npm: false
    project_has_bower: false
    project_npm_modules_path: node_modules
    # TODO can we get rid of these? check
    project_copy_previous_composer_vendors: false
    project_copy_previous_npm_modules: false
    project_copy_previous_bower_components: false
    restart_supervisor: false
    mailgun_api_key: "{{ lookup('env','MAILGUN_API_KEY') }}"
    secret_key: "{{ lookup('env','SECRET_KEY') }}"
    database_url: "{{ lookup('env','DATABASE_URL') }}"
    django_settings_module: "{{ lookup('env','DJANGO_SETTINGS_MODULE') }}"
    supervisor_user: "deploy"
    gunicorn_app: "{{ tgwf_domain_name }}"

    project_environment:
      MAILGUN_API_KEY: "{{ mailgun_api_key }}"
      DATABASE_URL: "{{ database_url }}"
      SECRET_KEY: "{{ secret_key }}"
      DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

    project_shared_children:
      - path: "/log"
        src: "logs"

    project_unwanted_items:
      - .git

    project_has_composer: no

    project_finalize: true

  roles:
    - f500.project_deploy

  tasks:
    - name: Template the .env file to latest release directory
      template:
        src: dotenv.j2
        dest: "{{ project_root }}/current/.env"
        owner: deploy
        group: deploy
        mode: "0755"
    - name: install python dependencies with pipenv
      shell: "pipenv install"
      args:
        chdir: "{{ project_root }}/current"
    - name: collect static files for django
      shell: "pipenv run ./manage.py collectstatic --no-input"
      args:
        chdir: "{{ project_root }}/current"
    - name: set up nginx server entry
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      become: yes

    - name: Create a symbolic to make nginx file appear in sites-enabled
      file:
        src: "/etc/nginx/sites-available/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        dest: "/etc/nginx/sites-enabled/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        state: link
      become: yes
    - name: set up script for running gunicorn, via supervisor
      template:
        src: "run_gunicorn.sh.j2"
        dest: "{{ project_root }}/current/run_gunicorn.sh"
      become: yes
    - name: set up supervisor entry
      template:
        src: "supervisor.gunicorn.conf.j2"
        dest: "/etc/supervisor/conf.d/{{ tgwf_domain_name }}.conf"
      become: yes

    - name: trigger restart for app with supervisor
      supervisorctl:
        name: "{{ gunicorn_app }}"
        state: restarted
      become: yes

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes
