---
- name: Deploy the TGWF django admin
  hosts:
    - all
  remote_user: "deploy"
  become: no

  vars:
    project_git_repo: "git@github.com:thegreenwebfoundation/admin-portal.git"
    project_deploy_strategy: git
    project_version: "master"
    project_local_path: "../"
    restart_supervisor: false
    supervisor_user: "deploy"
    gunicorn_app: "admin_web"
    project_unwanted_items:
      - .git

    project_finalize: true

  roles:
    - f500.project_deploy

  tasks:
    - name: set up directory for deploying django app
      file:
        path: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        state: directory
        mode: "0755"
        owner: deploy
        group: deploy
      become: yes

    - name: move .env file to shared directory
      template:
        src: "templates/dotenv.j2"
        dest: "{{ project_root }}/shared/.env"
      become: yes

    - name: Link .env to shared directory
      file:
        src: "{{ project_root }}/shared/.env"
        dest: "{{ project_root }}/current/.env"
        state: link

    - name: Link ./media to shared ./media directory
      file:
        src: "{{ project_root }}/shared/media"
        dest: "{{ project_root }}/current/media"
        state: link

    - name: Link ./data to shared ./data directory
      file:
        src: "{{ project_root }}/shared/data"
        dest: "{{ project_root }}/current/data"
        state: link

    - name: install pipenv and mariadb libraries for python
      apt:
        pkg:
          - python3-venv
          - python3-dev
          - build-essential
          - libmariadb3
          - libmariadb-dev
        state: present
      become: yes

    - name: install python dependencies with pipenv
      shell: "pipenv sync"
      args:
        chdir: "{{ project_root }}/current"
      environment:
        # make sure we install in the project root.
        # this way when we clear up old releases we also
        # remove the deps
        PIPENV_VENV_IN_PROJECT: 1

    - name: install node deps for building tailwind
      shell: "pipenv run ./manage.py tailwind install"
      args:
        chdir: "{{ project_root }}/current"

    - name: build minified tailwind css file
      shell: "pipenv run ./manage.py tailwind build"
      args:
        chdir: "{{ project_root }}/current"

    - name: build javascript bundle with rollup, using the local config file
      shell: "npx rollup --config"
      args:
        chdir: "{{ project_root }}/current/apps/theme/static_src"

    - name: collect static files for django
      shell: "pipenv run ./manage.py collectstatic --no-input"
      args:
        chdir: "{{ project_root }}/current"

    - name: set up nginx server entry
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      become: yes

    - name: Create a symbolic to make nginx file appear in sites-enabled
      file:
        src: "/etc/nginx/sites-available/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        dest: "/etc/nginx/sites-enabled/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        state: link
      become: yes

    - name: set up script for running gunicorn, via supervisor
      template:
        src: "run_gunicorn.sh.j2"
        dest: "{{ project_root }}/current/run_gunicorn.sh"
      become: yes

    - name: set up script for running workers, via supervisor
      template:
        src: "run_worker.sh.j2"
        dest: "{{ project_root }}/current/run_worker.sh"
      become: yes

    - name: set up supervisor entry for web
      template:
        src: "supervisor.gunicorn.conf.j2"
        dest: "/etc/supervisor/conf.d/{{ tgwf_domain_name }}_web.conf"
      become: yes

    - name: set up supervisor entry for worker
      template:
        src: "supervisor.worker.conf.j2"
        dest: "/etc/supervisor/conf.d/{{ tgwf_domain_name }}_worker.conf"
      become: yes

    - name: trigger restart for app with supervisor
      supervisorctl:
        name: "{{ gunicorn_app }}:"
        state: restarted
      become: yes

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes
