---
- name: Deploy the TGWF django admin
  hosts:
    - all
  remote_user: "deploy"
  become: no

  vars:
    project_git_repo: "git@github.com:thegreenwebfoundation/greenwebfoundation-admin.git"
    project_deploy_strategy: git
    project_version: "master"
    project_local_path: "../"
    project_has_npm: false
    project_has_bower: false
    project_npm_modules_path: node_modules
    # TODO can we get rid of these? check
    project_copy_previous_composer_vendors: false
    project_copy_previous_npm_modules: false
    project_copy_previous_bower_components: false
    restart_supervisor: false
    mailgun_api_key: "{{ lookup('env','MAILGUN_API_KEY') }}"
    secret_key: "{{ lookup('env','SECRET_KEY') }}"
    database_url: "{{ lookup('env','DATABASE_URL') }}"
    django_settings_module: "{{ lookup('env','DJANGO_SETTINGS_MODULE') }}"

    project_environment:
      MAILGUN_API_KEY: "{{ mailgun_api_key }}"
      DATABASE_URL: "{{ database_url }}"
      SECRET_KEY: "{{ secret_key }}"
      DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

    project_shared_children:
      - path: "/log"
        src: "logs"

    project_unwanted_items:
      - .git

    project_has_composer: no

    project_finalize: true

  roles:
    - f500.project_deploy

  tasks:
    - name: install deps
      shell: "pipenv install"
      args:
        chdir: "{{ project_root }}/current"
    - name: Template a file to /etc/files.conf
      template:
        src: dotenv.j2
        dest: "{{ project_root }}/current/.env"
        owner: deploy
        group: deploy
        mode: "0755"
    - name: collect static files for django
      shell: "pipenv run ./manage.py collectstatic"
      args:
        chdir: "{{ project_root }}/current"
    - name: set up nginx server
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-enabled/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        owner: deploy
        group: deploy
        mode: "0755"
        become: yes
    - name: set up supervisor entry
      template:
        src: "supervisor.gunicorn.conf.j2"
        dest: "/etc/supervisor/conf.d/{{ tgwf_domain_name }}.conf"
        owner: deploy
        group: deploy
        mode: "0755"
        become: yes
    # - name: trigger reload for supervisor
    # - name: trigger reload for nginx
