---
- name: Create green domain snapshot
  hosts:
    - all
  remote_user: "deploy"
  become: no

  tasks:
    - name: run management task to create domains snapshot
      shell: |
        source .venv/bin/acticate
        dotenv run -- ./manage.py dump_green_domains --upload
      args:
        chdir: "{{ project_root }}/current"
        executable: "/usr/bin/bash"
