---
- name: Provision the TGWF django web-app server
  hosts:
    # - app_servers
    # - app1.thegreenwebfoundation.org
    # - app2.thegreenwebfoundation.org
    # - app3.thegreenwebfoundation.org
    # - app4.thegreenwebfoundation.org

  remote_user: "deploy"
  become: false

  vars:
    # set up our deployment directories to be compatible with the project f500
    # deployment role
    create_deployment_dirs: true
    # set this to true will fetch the system requirements like python, mariadb, redis,
    # and so on
    install_system_reqs: true
    # decide about installing a recent version of node
    install_node: true
    # run an update of our front dependencies as part of the deploy. This is better
    # handled in source control, but if the front end will not build in deployment, this
    # is a workaround
    update_front_end_deps: true

  tasks:
    - name: Set up most recent timestamps directories
      ansible.builtin.include_tasks: "_create_deployment_directories.yml"
      when: create_deployment_dirs is true

    - name: Install all system dependencies
      ansible.builtin.include_tasks: "_add_system_dependencies.yml"
      when: install_system_reqs is true
      tags: [python]

    - name: Install all deploy dependencies
      ansible.builtin.include_tasks: "_install_deploy_dependencies.yml"
      when: install_system_reqs is true
