name: Deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  deploy:
    environment: prod
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use turnstyle to serialise deploys
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/deploy.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
          options: |
            --inventory ./ansible/inventories/prod.yml
        env:
          ANSIBLE_STDOUT_CALLBACK: yaml
          PYTHONDONTWRITEBYTECODE: 1
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          OBJECT_STORAGE_ENDPOINT: ${{ secrets.OBJECT_STORAGE_ENDPOINT }}
          OBJECT_STORAGE_REGION: ${{ secrets.OBJECT_STORAGE_REGION }}
          OBJECT_STORAGE_ACCESS_KEY_ID:  ${{ secrets.OBJECT_STORAGE_ACCESS_KEY_ID }}
          OBJECT_STORAGE_SECRET_ACCESS_KEY: ${{ secrets.OBJECT_STORAGE_SECRET_ACCESS_KEY }}
          OBJECT_STORAGE_BUCKET_NAME: ${{ secrets.OBJECT_STORAGE_BUCKET_NAME }}
          AMAZON_PROVIDER_ID: ${{ secrets.AMAZON_PROVIDER_ID }}
          AMAZON_REMOTE_API_ENDPOINT: ${{ secrets.AMAZON_REMOTE_API_ENDPOINT }}
          MICROSOFT_PROVIDER_ID: ${{ secrets.MICROSOFT_PROVIDER_ID }}
          MICROSOFT_LOCAL_FILE_DIRECTORY: ${{ secrets.MICROSOFT_LOCAL_FILE_DIRECTORY }}
          EQUINIX_PROVIDER_ID: ${{ secrets.EQUINIX_PROVIDER_ID }}
          EQUINIX_REMOTE_API_ENDPOINT: ${{ secrets.EQUINIX_REMOTE_API_ENDPOINT }}
          MAXMIND_USER_ID: ${{ secrets.MAXMIND_USER_ID }}
          MAXMIND_LICENCE_KEY: ${{ secrets.MAXMIND_LICENCE_KEY }}



